#!/usr/bin/env bash

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repository_dir=$(CDPATH= cd -- "$script_dir/.." && pwd)
shader_dir="$repository_dir/assets/shaders/bootstrap"
output_file="$repository_dir/src/engine/renderer/vulkan/triangle_shaders.hpp"

glslang_validator=${GLSLANG_VALIDATOR:-glslangValidator}
if ! command -v "$glslang_validator" >/dev/null 2>&1; then
    echo "glslangValidator is required to regenerate bootstrap shaders" >&2
    exit 1
fi

temporary_dir=$(mktemp -d)
trap 'rm -rf "$temporary_dir"' EXIT

"$glslang_validator" -V "$shader_dir/triangle.vert" -o "$temporary_dir/triangle.vert.spv"
"$glslang_validator" -V "$shader_dir/triangle.frag" -o "$temporary_dir/triangle.frag.spv"

word_count()
{
    stat -c '%s' "$1" | awk '{ print int($1 / 4) }'
}

write_array()
{
    local symbol=$1
    local input_file=$2
    local count
    count=$(word_count "$input_file")
    printf 'inline constexpr std::array<std::uint32_t, %s> %s = {\n' "$count" "$symbol"
    od -An -tu4 -v -w4 "$input_file" | awk '{ printf "    0x%08x,\n", $1 }'
    printf '};\n'
}

{
    printf '%s\n' '#pragma once' '' '#include <array>' '#include <cstdint>' '' \
        'namespace gameengine::renderer::vulkan::bootstrap {' '' \
        '// Generated by scripts/generate_bootstrap_shaders.sh.' \
        '// Do not edit this file manually.'
    write_array vertex_shader "$temporary_dir/triangle.vert.spv"
    write_array fragment_shader "$temporary_dir/triangle.frag.spv"
    printf '%s\n' '' '} // namespace gameengine::renderer::vulkan::bootstrap'
} > "$output_file"
